aliases:
    apply-Alexs-MacBook-Pro-2.local: nix run --impure home-manager/master -- -b bak switch --flake .#alex@Alexs-MacBook-Pro-2.local
    fleeks: cd /Users/alex/.local/share/fleek
    pinentry-mac: ~/.nix-profile/Applications/pinentry-mac.app/Contents/MacOS/pinentry-mac
bling: high
ejected: true
flakedir: .local/share/fleek
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
name: Fleek Configuration
packages:
    - rustup
    - haskell-language-server
    - zsh-autosuggestions
    - R
    - gnupg
    - nixpacks
    - cairo
    - kotlin
    - maven
    - nodePackages_latest.node-gyp
    - pinentry_mac
    - inetutils
    - nil
    - emacs
    - nixpkgs-fmt
    - ghc
    - cabal-install
    - kotlin-language-server
    - pkg-config
    - pixman
    - python39
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - helix
    - dircolors
shell: zsh
systems:
    - arch: aarch64
      hostname: Alexs-MacBook-Pro-2.local
      os: darwin
      username: alex
unfree: true
